site_name: "UAV Tracking Experiments"
site_description: "This is a documentation site for the UAV Tracking Experiments project."
site_url: "https://nathanbowness.github.io/UAV-Object-Tracking/"
docs_dir: "docs/"
site_dir: "site/"
theme:
  name: "material"
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.top  # Make sure top navigation is enabled
  navigation:
    sections: false  # Ensure sidebar sections are disabled

# Validation settings https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn


nav:
  - Configuration:
    - Configuration: configuration/configuration.md
    - CLI Arguments: configuration/cliArguments.md
    - Docker Image Details: configuration/dockerImageDetails.md
  - Instructions:
    - Running In Docker: guides/runningInDocker.md
    - Running the Radar Only: guides/runningTheRadar.md
    - Running the Video Processing Only: guides/runningVideoProcessing.md
    - Running On Previously Collected Data: guides/runningOnCollectedData.md
  - Setup: 
    - Setting Up Dev Environment: setup/devEnvironment.md
    - Enable Webcam In Container: setup/usingWebcamInContainer.md
    - Calibrating BB Coefficients: setup/calibratingBBCoeff.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
