# File for the tracking configuration

# Filter Configuration for different tracking algorithms
activeFilter: gmPHD
filters:
  # GM PHD 
  gmPHD:
    birthCovariance: 200 # covariance of the birth state in a distance of meters - by default this will set to the maximum resolution range of the sensors!
    expectedVelocity: 1 # expected velocity of the tracked object in meters per second
    noiseCovarianceDistance: 1 # covariance of the noise in a distance of meters
    defaultCovarianceDistance: 1 # default covariance of the tracked object in a distance of meters
    defaultConvarianceVelocity: 0.3 # default covariance of the tracked object in a velocity of meters per second
    probabilityOfDetection: 0.8 # probability of detection
    probabilityOfDeath: 0.01 # probability of death
    clusterRate: 7.0

    mergeThreshold: 5 # Threshold Squared Mahalanobis distance
    pruneThreshold: 0.00000001  # Threshold component weight i.e. 1e-8
    stateThreshold: 0.25

# Detection clustering configuration
minDetectionsToCluster: 1
maxDistanceBetweenClusteredObjectsM: 2

# Tracking plot configuration 
trackTailLength: 0.1 # O to 1, 0 means no tail, 1 means full tail

# Configuration for processing and memory management
maxTrackQueueSize: 200

# Show the Stone Soup tracking plot when the program exits
showTrackingPlot: True

# Output path for the tracking results
saveTrackingResults: True
outputDirectory: '/output'

