# File to configuration the video processing -- sepcifically for the Anker Webcam I have

# Configuration for the Yolo Processing
modelWeights: "yolov8n.pt"
saveRawImages: False
saveProcessedVideo: True
outputDirectory: "/output"
videoSource: "0"
confidenceThreshold: 0.3
iouThreshold: 0.5
videoStream: True

# Configuration for showing the Live Video During Yolo Processing 
showBoxesInVideo: True
showVideo: True

# Camera Details
cameraHorizontalFOV: 65
cameraZoomFactor: 1.0
imageWidth: 640
imageHeight: 480


