name: Jetson Jetpack5 - Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout branch
        uses: actions/checkout@v3

      # Get the commit count from the repository to tag the image
      - name: Get Commit Count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Dockerfile-jetson-jetpack5
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-jetson-jetpack5
          platforms: linux/arm64 # Specify ARM64 platform for the Jetson
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/uav-experiments:latest-jetson-jetpack5
            ${{ secrets.DOCKER_USERNAME }}/uav-experiments:0.1.${{ env.COMMIT_COUNT }}-jetson-jetpack5
