name: Linux - Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      # Get the commit count from the repository to tag the image
      - name: Get Commit Count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Dockerfile (Default)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/uav-experiments:latest
            ${{ secrets.DOCKER_USERNAME }}/uav-experiments:0.1.${{ env.COMMIT_COUNT }}
